2021-03-19 17:59:23.367689: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-03-19 17:59:23.368507: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/om2/user/gretatu/anaconda/envs/control-neural/lib/python3.6/site-packages/pandas/io/pickle.py", line 182, in read_pickle
    return pickle.load(f)
ModuleNotFoundError: No module named 'neural_nlp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_activations.py", line 176, in <module>
    x = pd.read_pickle(STIMULI_TO_PKL_MAP[key])
  File "/om2/user/gretatu/anaconda/envs/control-neural/lib/python3.6/site-packages/pandas/io/pickle.py", line 187, in read_pickle
    return pc.load(f, encoding=None)
  File "/om2/user/gretatu/anaconda/envs/control-neural/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 249, in load
    return up.load()
  File "/om2/user/gretatu/anaconda/envs/control-neural/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/om2/user/gretatu/anaconda/envs/control-neural/lib/python3.6/pickle.py", line 1347, in load_stack_global
    self.append(self.find_class(module, name))
  File "/om2/user/gretatu/anaconda/envs/control-neural/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 189, in find_class
    return super().find_class(module, name)
  File "/om2/user/gretatu/anaconda/envs/control-neural/lib/python3.6/pickle.py", line 1388, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'neural_nlp'
